### PR TITLE
Highlightblocks

### PR DESCRIPTION
**Pull request by foocil**
Highlight the block that is "mouseover" with a red border of 5 (red and 5 can be modified depending of what we will decide)

### CODE REVIEW

**Comment by nkcr** [comment]
That will be really useful! I think we could even highlight all the blocks found by default, and make the hover highlight even more the block (or maybe change its color?).

**Comment by Anthony-Iozzia** [comment]
Nice!

**Comment by foocil** [comment]
Mon soucis actuel est que si le block n'a pas été load au moment du browse, il n'y a pas de highlight...

**Comment by foocil** [comment]
TO BE ADDED: highlight the block that has been clicked on

**Comment by foocil** [comment]
1: Highlight the block that has been clicked on. If another one is clicked, then the previous one will be changed. We need to choose the color of the blocks.
2: Highlight the block found in the browsing with a stroke for the ones who are displayed, highlight with a different color and width the one with mouthover. 
3:In case of reloading blocks, highlight works!

**Pull request merged**
