### PR TITLE
Instruction display

### PR DESCRIPTION
**Pull request by foocil**
TODO:
- [ ] Hash, InstanceID shown the same way with the transactions
- [x] Open all button at first
- [ ] Border of button to see them better
- [x] Number of instruction inside one transaction
- [x] "Bullet point" to see the different instruction
- [x] Clearer search button
- [ ] mouseover in all "child"?
- [x] both containers next to each other if possible

### CODE REVIEW

**Comment by foocil** [comment]
Styling of the interface will be in this PR

**Comment by foocil** [comment]
Problem with the footer: it does not response to the change of size window!

**Comment by nkcr** [comment]
Cool! Some remarks:

- don't use an absolute position (and either `bottom:`) for the footer, like so it will naturally be positioned at the bottom of your page
- for your `blockDetailcontainer` and `container` you should invalidate the `flex: 1` property when the window is bellow 1000:

```
@media only screen and (max-width: 1000px) {
    div.block-infos {
        flex-direction: column;
    }
    div.blockDetailcontainer,
    div.container {
        flex: none;
    }
}
```

then you can set to them a `max-height: 500px` instead of you `max-height: 1000`.

**Comment by nkcr** [comment]
Concerning the content of the footer, I would keep it much lighter, a bit like in http://status.dedis.ch/#/:

```
© DEDIS 2020 - Student Project by Anthony Iozza and Julien von Felten - v.1.0.11 - Github(link)
```

In design the rule "less is more" often applies. The result of often better when things stay minimalist.

**Comment by foocil** [comment]
Footer is done like in status.dedis.ch. I guess you are right :D "less is more"

**Comment by foocil** [comment]
@nkcr Anything else I could change? Or I can merge it?

**Comment by nkcr** [comment]
Ok for me 👍

**Pull request merged**
